// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBi9iiNr3Xqe-Ax8vcNom1guPBDYI_Vvis',
    appId: '1:196635980113:web:c6e8a0848db0dd2572a370',
    messagingSenderId: '196635980113',
    projectId: 'food-delivery-c973c',
    authDomain: 'food-delivery-c973c.firebaseapp.com',
    storageBucket: 'food-delivery-c973c.appspot.com',
    measurementId: 'G-8N04ZB5YB2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPEZcHy_BFCy9reI6-uRQ2Km2JK1b0PBM',
    appId: '1:196635980113:android:12219e01b249232f72a370',
    messagingSenderId: '196635980113',
    projectId: 'food-delivery-c973c',
    storageBucket: 'food-delivery-c973c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASUrMJ9E0Rhe1-rGo_afsJ0dGDsYHSXM8',
    appId: '1:196635980113:ios:f4f72f62e6cbfdf572a370',
    messagingSenderId: '196635980113',
    projectId: 'food-delivery-c973c',
    storageBucket: 'food-delivery-c973c.appspot.com',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASUrMJ9E0Rhe1-rGo_afsJ0dGDsYHSXM8',
    appId: '1:196635980113:ios:f4f72f62e6cbfdf572a370',
    messagingSenderId: '196635980113',
    projectId: 'food-delivery-c973c',
    storageBucket: 'food-delivery-c973c.appspot.com',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBi9iiNr3Xqe-Ax8vcNom1guPBDYI_Vvis',
    appId: '1:196635980113:web:6c69b69e760181e872a370',
    messagingSenderId: '196635980113',
    projectId: 'food-delivery-c973c',
    authDomain: 'food-delivery-c973c.firebaseapp.com',
    storageBucket: 'food-delivery-c973c.appspot.com',
    measurementId: 'G-CFVN8EMTFD',
  );
}
